package sch.man.com.unused;
// Generated May 15, 2018 8:48:12 PM by Hibernate Tools 4.3.1



/**
 * Studentdetail generated by hbm2java
 */
public class Studentdetail  implements java.io.Serializable {


     private String userid;
     private String firstname;
     private String lastname;
     private String gender;
     private String dob;
     private String address;
     private String phone;
     private String email;
     private String password;

    public Studentdetail() {
    }

	
    public Studentdetail(String userid) {
        this.userid = userid;
    }
    public Studentdetail(String userid, String firstname, String lastname, String gender, String dob, String address, String phone, String email, String password) {
       this.userid = userid;
       this.firstname = firstname;
       this.lastname = lastname;
       this.gender = gender;
       this.dob = dob;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.password = password;
    }
   
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


